dataset_path = "../../data/vietnam/vietnam_[2017-2022]_fix.csv"

province_path = "../../data_sung/province.xlsx"

province_msn = "../../data_sung/province_msn.xlsx"

geo_json_path = "../Vietnam_provinces.geojson"

list_provinces = [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Thành phố Hồ Chí Minh",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
]

list_eng_province = [
    "An Giang Province",
    "Ba Ria - Vung Tau Province",
    "Bac Giang Province",
    "Bac Kan Province",
    "Bac Lieu Province",
    "Bac Ninh Province",
    "Ben Tre Province",
    "Binh Dinh Province",
    "Binh Duong Province",
    "Binh Phuoc Province",
    "Binh Thuan Province",
    "Ca Mau Province",
    "Can Tho City",
    "Cao Bang Province",
    "Da Nang City",
    "Dak Lak Province",
    "Dak Nong Province",
    "Dien Bien Province",
    "Dong Nai Province",
    "Dong Thap Province",
    "Gia Lai Province",
    "Ha Giang Province",
    "Ha Nam Province",
    "Ha Noi City",
    "Ha Tinh Province",
    "Hai Duong Province",
    "Hai Phong City",
    "Hau Giang Province",
    "Ho Chi Minh City",
    "Hoa Binh Province",
    "Hung Yen Province",
    "Khanh Hoa Province",
    "Kien Giang Province",
    "Kon Tum Province",
    "Lai Chau Province",
    "Lam Dong Province",
    "Lang Son Province",
    "Lao Cai Province",
    "Long An Province",
    "Nam Dinh Province",
    "Nghe An Province",
    "Ninh Binh Province",
    "Ninh Thuan Province",
    "Phu Tho Province",
    "Phu Yen Province",
    "Quang Binh Province",
    "Quang Nam Province",
    "Quang Ngai Province",
    "Quang Ninh Province",
    "Quang Tri Province",
    "Soc Trang Province",
    "Son La Province",
    "Tay Ninh Province",
    "Thai Binh Province",
    "Thai Nguyen Province",
    "Thanh Hoa Province",
    "Thua Thien Hue Province",
    "Tien Giang Province",
    "Tra Vinh Province",
    "Tuyen Quang Province",
    "Vinh Long Province",
    "Vinh Phuc Province",
    "Yen Bai Province",
]

list_features = [
    "Humidity",
    "Dew point",
    "Temperature",
    "Rain",
    "Cloud",
    "Wind",
    "Dir",
    "Pressure",
    "Gust",
    "Weather",
]

list_years = ["All", "2022", "2021", "2020", "2019", "2018", "2017"]

list_months = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]

month_dict = {
    "1": "January",
    "2": "February",
    "3": "March",
    "4": "April",
    "5": "May",
    "6": "June",
    "7": "July",
    "8": "August",
    "9": "September",
    "10": "October",
    "11": "November",
    "12": "December",
}

unit_mapping = {
    "Humidity": "%",
    "Dew point": "°C",
    "Temperature": "°C",
    "Rain": "mm",
    "Cloud": "%",
    "Wind": "km/h",
    "Dir": "°",
    "Pressure": "mb",
    "Gust": "km/h",
}

name_dict_ve = dict(zip(list_provinces, list_eng_province))

name_dict_ev = dict(zip(list_eng_province, list_provinces))